### PR TITLE
add links and installation instructions (fixes #1)

### LINKED ISSUE #1: Installation instructions?
Sorry for the noob question, but could you add some instructions to the README on how to install it and set it up for auto-launch? I'll be happy to beta-test this and contribute documentation to help others :)

### PR DESCRIPTION
**Pull request by waldyrious**
including a fix of the package name: python-xcb --> python-xpyb

### CODE REVIEW

**Comment by waldyrious** [comment]
Hey @abyrd, I know this is fairly old, but I wonder if you'd have the chance to take a look sometime soon. Let me know if anything concerns you -- I can edit the commits if necessary.

**Comment by abyrd** [comment]
Hello @waldyrious, I haven't been maintaining this because I haven't used an X window server for a few years. I didn't even realize there were PRs open. I'm reviewing it now. A first comment though: it's always helpful to have PR descriptions that give additional information and context, expanding on the title and explaining why things were changed. Of course in this case the changes are rather simple, but a good description often makes the difference between a PR being handled quickly and one lingering without resolution.

**Comment by waldyrious** [comment]
Yes, that's a good point. Nowadays I'm more careful with that (I'd also have split the commits into more atomic changes).

Btw I've fixed the content conflict now that the other PR has been merged.

**Comment by abyrd** [comment]
Thanks!

**Pull request merged**
